# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer

                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os

from .plugin_utils.installer import WINMOL_VENV_NAME, \
    ensure_venv, ensure_dependencies, download_models


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WINMOLAnalyzer
 class from file WINMOLAnalyzer
.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    project_path = os.path.dirname(__file__)

    venv_path = ensure_venv(
        os.path.join(
            project_path,
            WINMOL_VENV_NAME
        )
    )
    ensure_dependencies(venv_path)
    
    

    from .winmol_analyzer import WINMOLAnalyzer
    return WINMOLAnalyzer(iface, venv_path)
