# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer

                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os

from .plugin_utils.installer import ensure_dependencies


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WINMOLAnalyzer
 class from file WINMOLAnalyzer
.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    # TODO: set proper path
    dep_path = os.path.dirname(__file__) + "/dependencies"
    if not os.path.exists(dep_path):
        os.makedirs(dep_path)
    print(dep_path)
    ensure_dependencies(dep_path)

    from .winmol_analyzer import WINMOLAnalyzer
    return WINMOLAnalyzer(iface)
