name: Create and release archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'WINMOL_Analyser_QGIS_Plugin.zip'
          exclusions: '*.git* documentation/* winmol_venv/* Dockerfile startDocker.sh .github/* standalone/input/* standalone/output/* standalone/model/* standalone/pred/*'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
