name: Create and release archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: WINMOL_Analyzer
      - name: Archive Release
        uses: montudor/action-zip@v1
        with:
          args: zip -r WINMOL_Analyzer_QGIS_Plugin.zip WINMOL_Analyzer -x "*.git*" -x "*documentation/*" -x "*winmol_venv/*" -x "*Dockerfile" -x "*startDocker.sh" -x "*.github/*" -x "*standalone/input/*" -x "*standalone/output/*" -x "*standalone/model/*" -x "*standalone/pred/*" -x "*__pycache*" -x "*pylintrc"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "WINMOL_Analyser_QGIS_Plugin.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
