name: Update metadata version on release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Debug repository files
        run: ls -R

      - name: Update metadata.txt with release version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          python .github/scripts/update_metadata_version.py "$VERSION"

      - name: Commit updated metadata.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metadata.txt
          git commit -m "Update version in metadata.txt to $VERSION" || echo "No changes to commit"
          git push
