name: Update metadata version on release

on:
  release:
    types: [published]  # Runs when a new release is published

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  	with:
    	  path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Update metadata.txt with release version
        run: |
          python .github/scripts/update_metadata_version.py "${GITHUB_REF_NAME}"

      - name: Commit updated metadata.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metadata.txt
          git commit -m "Update version in metadata.txt to ${GITHUB_REF_NAME}"
          git push
